# Generated by Django 3.2.13 on 2022-06-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
